# Generated by Django 5.0.6 on 2024-06-04 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='cargo',
            field=models.CharField(choices=[('gerente', 'Gerente'), ('tecnico', 'Técnico'), ('asistente', 'Asistente')], default='tecnico', max_length=25),
        ),
    ]
