# Generated by Django 5.0.6 on 2025-02-09 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_remove_cliente_correo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='celular',
            name='imei',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
