# Generated by Django 5.0.6 on 2024-06-04 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobros', '0002_productoenticket'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='detallecobro',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='detallecobro',
            name='empleado',
        ),
        migrations.RemoveField(
            model_name='detallecobro',
            name='productos',
        ),
        migrations.RemoveField(
            model_name='detallecobro',
            name='servicios',
        ),
        migrations.RemoveField(
            model_name='productoenticket',
            name='producto',
        ),
        migrations.RemoveField(
            model_name='productoenticket',
            name='servicio',
        ),
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Producto', 'Producto'), ('Reparación', 'Reparación')], max_length=10)),
                ('nombre_producto', models.CharField(blank=True, max_length=255, null=True)),
                ('cantidad', models.IntegerField(default=1)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='cobros.venta')),
            ],
        ),
        migrations.DeleteModel(
            name='Cobro',
        ),
        migrations.DeleteModel(
            name='DetalleCobro',
        ),
        migrations.DeleteModel(
            name='ProductoEnTicket',
        ),
    ]
