# Generated by Django 5.0.6 on 2024-06-28 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobros', '0004_detalleventa_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleventa',
            name='costo',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
