# Generated by Django 5.0.6 on 2024-06-25 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0005_servicio_activo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Celular',
        ),
    ]
