# Generated by Django 5.0.6 on 2024-06-25 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0006_delete_celular'),
    ]

    operations = [
        migrations.AddField(
            model_name='accionesservicio',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
