# Generated by Django 5.0.6 on 2024-06-25 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0008_alter_accionesservicio_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='accionesservicio',
            name='estado',
            field=models.CharField(choices=[('ingresado', 'Ingresado'), ('en_proceso', 'En Proceso'), ('finalizado', 'Finalizado'), ('entregado', 'Entregado')], default='ingresado', max_length=20),
        ),
    ]
