# Generated by Django 5.0.6 on 2024-06-28 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0009_accionesservicio_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
